name: PuntoExtra
on:
  schedule:
    - cron: '25 22 * * 1,3'  

jobs:
  git_log:
    runs-on: ubuntu-latest
    steps:
    - name: Check out repository
      uses: actions/checkout@v3
    - name: Show Git Log
      run: git log

  pull_request:
    runs-on: ubuntu-latest
    steps:
    - name: Check out repository
      uses: actions/checkout@v3