name: Tarea_normal

on:
  pull_request:
  push:
    paths:
      - 'tareas/Schafler_And/**'
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Check out repository
      uses: actions/checkout@v3
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1
    - name: Build Docker Image
      run: |
        docker build -t git_act tareas/Schafler_And
    - name: Log in to Docker Hub
      run: docker login -u ${{ secrets.DOCKERHUB_USERNAME }} -p ${{ secrets.DOCKERHUB_TOKEN }}
    - name: Tag Docker Image
      run: docker tag git_act ${{ secrets.DOCKERHUB_USERNAME }}/git_act:latest
    - name: Push Docker Image to Docker Hub
      run: docker push ${{ secrets.DOCKERHUB_USERNAME }}/git_act:latest
    - name: Run Docker Container
      run: |
        docker run ${{ secrets.DOCKERHUB_USERNAME }}/git_act > output.log
    - name: Print Docker Output
      run: |
        cat output.log
