name: TareaGitHubActions

on:
  push:
    paths:
      - 'tareas/VictorEsparza/*'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2
      
    - name: Build Docker image
      run: docker build -t ${{ secrets.DOCKER_USERNAME }}/tareaGHActions:latest .
      
    - name: Log into Docker Hub
      run: echo "${{ secrets.DOCKER_TOKEN }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin
      
    - name: Push Docker image to Docker Hub
      run: docker push ${{ secrets.DOCKER_USERNAME }}/tareaGHActions:latest
      
    - name: Run tests
      run: docker run ${{ secrets.DOCKER_USERNAME }}/tareaGHActions:latest
