name: Actions_Victor

on:
  pull_request:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2
      
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1

    - name: Build Docker image
      run: docker build -t ${{ secrets.GITACT_HW_USER}}/tareaghactions:latest tareas/VictorEsparza
      
    - name: Log into Docker Hub
      run: echo "${{ secrets.GITACT_HW_KEY }}" | docker login -u "${{ secrets.GITACT_HW_USER}}" --password-stdin
      
    - name: Push Docker image to Docker Hub
      run: docker push ${{ secrets.GITACT_HW_USER }}/tareaghactions:latest
      
    - name: Run tests
      run: docker run ${{ secrets.GITACT_HW_USER }}/tareaghactions:latest
